### ISSUE TITLE
Button B11 causes exception on Layer A

### ISSUE THREAD

**Issue by BeansIsFat** [peterdikant/xair-remote#6]
Pressing button B11 on Layer A throws an exception.
Pressing button B11 on Layer B does not throw an exception.
Here is the traceback:
```Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "xair-remote/lib/midicontroller.py", line 134, in midi_listener
    self.button_pushed(self.MIDI_BUTTONS.index(msg.note))
  File "xair-remote/lib/midicontroller.py", line 162, in button_pushed
    self.state.toggle_channel_mute(button)
  File "xair-remote/lib/mixerstate.py", line 115, in toggle_channel_mute
    if self.banks[self.active_bank][channel] != None:
IndexError: list index out of range```

**Comment by peterdikant** [comment]
Fixed it in commit a8568b6d5e3629305c38c094c474630fcc4b2bd4
